name: CI bar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "bar/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd bar
          echo Hello, `pwd` !
