name: CI {{ROUTE}}

on:
  # push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "{{ROUTE}}/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd {{ROUTE}}
          echo Hello, `pwd` !
